lib/ex_jagaimo_blog_web/router.ex
defmodule ExJagaimoBlogWeb.Router do
  use ExJagaimoBlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :put_root_layout, {ExJagaimoBlogWeb.LayoutView, :root}
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ExJagaimoBlogWeb do
    pipe_through :browser

    get "/", LandingController, :index
    resources "/posts", PostController
    resources "/blogs", BlogController

    scope "/archive" do
      get "/tags/*tags", PostController, :index, as: :tags_archive
      get "/", PostController, :index, as: :archive
      get "/:year", PostController, :index
      get "/:year/:month", PostController, :index
      get "/:year/:month/:day", PostController, :index
      get "/:year/:month/:day/:id", PostController, :show, as: :post_permalink
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", ExJagaimoBlogWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ExJagaimoBlogWeb.Telemetry
    end
  end
end

lib/ex_jagaimo_blog_web/controllers/landing_controller.ex
defmodule ExJagaimoBlogWeb.LandingController do
  use ExJagaimoBlogWeb, :controller

  alias ExJagaimoBlog.Blogs
  alias ExJagaimoBlog.Blogs.Blog
  import ExJagaimoBlogWeb.Helpers.BlogHelper

  def action(conn, _) do
    conn = maybe_set_blog(conn)
    args = [conn, conn.params]
    apply(__MODULE__, action_name(conn), args)
  end

  def index(%Plug.Conn{assigns: %{blog: %Blog{} = blog}} = conn, _params) do
    posts = Blogs.list_latest_posts_for_blog(blog, 6)

    tag_cloud =
      ExJagaimoBlog.Tags.list_ranked_tags_by_blog(blog)
      |> ExJagaimoBlog.Tags.normalize_tag_sizes()
      |> ExJagaimoBlog.Tags.sort_tag_sizes_by_name()

    {top_post, highlights} =
      case posts do
        [top_post | highlights] -> {top_post, highlights}
        _other -> {nil, []}
      end

    render(conn, "index.html",
      top_post: top_post,
      highlights: highlights,
      title: blog.name,
      tag_cloud: tag_cloud
    )
  end

  def index(conn, _params) do
    conn
    |> put_flash(:info, gettext("This domain is not yet configured."))
    |> redirect(to: Routes.blog_path(conn, :index))
  end
end

lib/ex_jagaimo_blog_web/views/landing_view.ex
defmodule ExJagaimoBlogWeb.LandingView do
  use ExJagaimoBlogWeb, :view
end

lib/ex_jagaimo_blog_web/templates/landing/_links.html.eex
<ul>
    <%= for post <- @posts do%>
      <li><%= link post.title, to: permalink_path(@conn, post), class: "text-white underline hover:text-yellow-300"%></li>
    <% end %>
</ul>

<%= link gettext("More posts..."), to: Routes.archive_path(@conn, :index), class: "text-white pt-2 hover:text-yellow-300"%>

lib/ex_jagaimo_blog_web/templates/landing/_tag_cloud.html.eex
<%= for {tag, weight} <- @tag_cloud do %>
  <%= link tag, to: Routes.tags_archive_path(@conn, :index, [tag]), class: "inline-block bg-yellow-100 p-2", style: "font-size: #{trunc(weight)+8}pt;" %>
<% end %>

lib/ex_jagaimo_blog_web/templates/landing/_top_post.html.eex
<section>
    <main>
      <h1 class="text-6xl hover:underline"><%=link @post.title, to: Routes.post_path(@conn, :show, @post) %></h1>
        <address class="p-1"><%= @post.user.name %></address>
        <div>
          <%= Timex.format!(@post.publish_at, "{Mfull} {D}, {YYYY}, {h12}:{m} {AM}")%>
        </div>

      <article class="post">
        <%= raw @post.story %>
      </article>

    </main>

</section>

lib/ex_jagaimo_blog_web/templates/landing/index.html.eex
<section>
  <h1 class="p-3 text-3xl"><%= @blog.name %></h1>
  <h2 class="p-3"><%= @blog.subheading %></h2>

  <main class="p-3">
    <%= if @top_post do %>
      <%= render "_top_post.html", conn: @conn, post: @top_post %>
    <% end %>
  </main>
  <section class="bg-blue-500 p-4">
      <%= render("_links.html", conn: @conn, posts: @highlights) %>
  </section>
  <section class="bg-yellow-300 p-4">
    <%= render("_tag_cloud.html", conn: @conn, tag_cloud: @tag_cloud) %>
  </section>

</section>